name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
  
    runs-on: ${{ matrix.os }}

    steps:
    - name: Prepare
      uses: ./.github/workflows/prepare
        
    - name: Run tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: clean test
