name: Update Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Java CI with Gradle" ]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      version: ${{ steps.versioning.outputs.VERSION_INFORMATION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Create Shadow JAR
        run: ./gradlew shadowJar

      - name: Get current version
        run: echo "VERSION_INFORMATION=$(./gradlew -q version)" >> $GITHUB_ENV

      - name: Cache Shadow JAR
        uses: actions/cache/save@v3
        with:
          path: ./build/libs/*-all.jar
          key: build-${{ env.VERSION_INFORMATION }}-${{ github.run_id }}
          enableCrossOsArchive: true

      - name: Add Shadow JAR to the release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "${{github.workspace}}/build/libs/*-all.jar"
          tag: ${{ env.VERSION_INFORMATION }}
          allowUpdates: true

      - name: Export version
        id: versioning
        run: echo "version=${{ env.VERSION_INFORMATION }}" >> $GITHUB_OUTPUT

  release:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: build
    
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          runner-os: ${{ matrix.os }}

      - name: Load Cache
        uses: actions/cache/restore@v3
        with:
          path: ./build/libs/*-all.jar
          key: build-${{ needs.build.outputs.version }}-${{ github.run_id }}
          enableCrossOsArchive: true

      - name: Create installer per OS
        run: ./gradlew jpackage -PignoreShadow

      - name: Create additional artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: ./gradlew jpackage -PignoreShadow -Ptype=msi

      - name: Update Release with artifacts
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "${{github.workspace}}/build/jpackage/*"
          tag: ${{ needs.build.outputs.version }}
          allowUpdates: true