name: Update Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Java CI with Gradle" ]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          runner-os: ${{ matrix.os }}

      - name: Get current version on Linux
        if: matrix.os == 'ubuntu-latest'
        run: echo "VERSION_INFORMATION=$(./gradlew -q version)" >> $GITHUB_ENV

      - name: Get current version on Windows
        if: matrix.os == 'windows-latest'
        run: echo "VERSION_INFORMATION=$(./gradlew -q version)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create Shadow JAR
        run: ./gradlew shadowJar

      - name: Create installer per OS
        run: ./gradlew jpackage

      - name: Create additional installer for Windows
        if: matrix.os == 'windows-latest'
        run: ./gradlew jpackage -Ptype=msi

      - name: Update Release with artifacts
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "${{github.workspace}}/build/libs/*-all.jar,${{github.workspace}}/build/jpackage/*"
          tag: ${{ env.VERSION_INFORMATION }}
          allowUpdates: true